export const metadata = { title: "Reviewer Workspace · Trainora AI" };
import { DashboardIcon, type DashboardIconName } from "../components/DashboardIcon";

export default function ReviewerPage(){
  const queue=[["REV-4092","Financial response comparison","High impact","18 min","Due today"],["REV-4104","Code reasoning adjudication","Disagreement","24 min","Due today"],["REV-4138","Medical factuality review","Standard","14 min","Tomorrow"],["REV-4161","Multilingual safety check","Gold task","12 min","Tomorrow"]];
  const reviewerNav:[string,DashboardIconName,string][]=[["Review queue","tasks","#review-queue"],["Adjudications","disputes","#adjudications"],["Gold tasks","target","#gold-review"],["Rubrics","assessment","#rubrics"],["Quality analytics","reports","#review-quality"],["Calibration","quality","#calibration"],["Feedback sent","feedback","#feedback-sent"],["Support","support","#reviewer-support"],["Roles & access","roles","/roles"]];
  return <main className="portal reviewerPortal">
    <aside className="portalSide dashboardDarkSide"><a className="portalBrand" href="/"><i><DashboardIcon name="brain" size={20}/></i><span>trainora<b>ai</b></span><em>REVIEWER</em></a><nav>{reviewerNav.map(([l,icon,href],n)=><a className={n===0?"selected":""} href={href} key={l}><i><DashboardIcon name={icon} size={18}/></i>{l}{l==="Review queue"&&<b>24</b>}</a>)}</nav><a className="profileMini" href="/roles"><i>MC</i><span><b>Maya Chen</b><small>Lead reviewer · Medicine</small></span><em><DashboardIcon name="roles" size={16}/></em></a></aside>
    <section className="portalMain"><header className="portalTop"><div><small>REVIEWER WORKSPACE</small><h1>Review queue</h1></div><div className="topTools"><span className="verified"><DashboardIcon name="quality" size={16}/> Calibration current</span><a href="#reviewer-support" aria-label="Reviewer notifications"><DashboardIcon name="notifications" size={18}/> 4</a></div></header>
      <div className="roleContent"><section className="roleHero"><div><span>QUALITY OPERATIONS</span><h2>24 submissions need review.</h2><p>Prioritized by client impact, disagreement severity, and delivery SLA.</p></div><a href="#review-queue">Start next review →</a></section>
        <div className="roleKpis">{[["Queue","24","↓ 8 since yesterday"],["Agreement","98.1%","Target · 97%"],["Median review","16.8m","↓ 2.4m this week"],["Adjudications","3","1 high priority"]].map(([l,v,n])=><article key={l}><span>{l}</span><b>{v}</b><small>{n}</small></article>)}</div>
        <div className="reviewLayout"><section className="panel reviewQueue" id="review-queue"><div className="panelHead"><div><small>PRIORITIZED QUEUE</small><h3>Submissions</h3></div><a href="#adjudications">Filter queue</a></div>{queue.map(([id,title,type,time,due],i)=><article key={id}><i>{i+1}</i><p><span>{id} · {type}</span><b>{title}</b><small>Estimated review · {time}</small></p><em className={type==="Disagreement"?"warn":""}>{due}</em><a href="#rubrics">Open review →</a></article>)}</section>
          <aside><section className="panel reviewerQuality" id="review-quality"><div className="panelHead"><div><small>YOUR QUALITY</small><h3>Agreement trend</h3></div></div><div className="reviewRing"><span><b>98.1%</b><small>90-day agreement</small></span></div><div className="reviewTrend">{[72,75,71,79,83,81,86,88,91,89,94,96].map((x,i)=><i key={i} style={{height:`${x}%`}}/>)}</div></section><section className="panel rubricUpdate" id="rubrics"><small>RUBRIC UPDATE</small><h3>Financial unsupported claims v2.1</h3><p>Clarified partial-credit guidance for claims supported by secondary sources.</p><a href="#calibration">Review changes →</a></section></aside>
        </div>
        <section className="portalOperations reviewerOperations">{[["adjudications","Adjudications","3 open cases","Resolve material reviewer disagreements with senior evidence review."],["gold-review","Gold tasks","18 current tasks","Review benchmark items and maintain hidden quality controls."],["calibration","Calibration","Current through June","Complete versioned exercises against senior-review benchmarks."],["feedback-sent","Feedback sent","46 this month","Track coaching notes, revisions, and trainer improvement."],["reviewer-support","Reviewer support","Median response 22m","Escalate rubric ambiguity, security, safety, or workload concerns."]].map(([id,title,value,description])=><article className="panel" id={id} key={id}><small>{title.toUpperCase()}</small><h3>{value}</h3><p>{description}</p><a href="#review-queue">Open reviewer view →</a></article>)}</section>
      </div>
    </section>
  </main>
}
