export const metadata = { title: "Client Workspace · Trainora AI" };
import { DashboardIcon, type DashboardIconName } from "../components/DashboardIcon";

export default function ClientPage(){
  const clientNav:[string,DashboardIconName,string][]=[["Overview","activity","#overview"],["Projects","projects","#projects"],["Workforce","users","#workforce"],["Tasks","tasks","#tasks"],["Quality","quality","#quality"],["Datasets","database","#datasets"],["Analytics","reports","#analytics"],["Billing","billing","#billing"],["API & integrations","integrations","#integrations"],["Roles & access","roles","/roles"]];
  return <main className="portal clientPortal">
    <aside className="portalSide dashboardDarkSide"><a className="portalBrand" href="/"><i><DashboardIcon name="brain" size={20}/></i><span>trainora<b>ai</b></span><em>CLIENT</em></a><nav>{clientNav.map(([l,icon,href],n)=><a className={n===0?"selected":""} href={href} key={l}><i><DashboardIcon name={icon} size={18}/></i>{l}</a>)}</nav><a className="profileMini" href="/roles"><i>NS</i><span><b>Northstar AI</b><small>Client workspace</small></span><em><DashboardIcon name="roles" size={16}/></em></a></aside>
    <section className="portalMain"><header className="portalTop"><div><small>NORTHSTAR AI</small><h1>Portfolio overview</h1></div><div className="topTools"><label><DashboardIcon name="search" size={17}/><input placeholder="Search projects…"/></label><a href="#alerts" aria-label="Workspace alerts"><DashboardIcon name="notifications" size={18}/> 2</a><a href="#projects"><DashboardIcon name="projects" size={17}/> New project</a></div></header>
      <div className="roleContent" id="overview"><section className="roleHero clientHero"><div><span>CLIENT CONTROL CENTER</span><h2>Your AI data portfolio is on track.</h2><p>Three active projects, 642 verified experts, and 96.9% average reviewer agreement.</p></div><a href="#projects">Create project →</a></section>
        <div className="roleKpis">{[["Active projects","3","1 launching next week"],["Tasks delivered","42,680","↑ 12.4% this month"],["Review agreement","96.9%","Above 96% target"],["Approved spend","$284k","68% utilized"]].map(([l,v,n])=><article key={l}><span>{l}</span><b>{v}</b><small>{n}</small></article>)}</div>
        <div className="clientGrid"><section className="panel clientProjects" id="projects"><div className="panelHead"><div><small>PROJECT PORTFOLIO</small><h3>Delivery and quality</h3></div><a href="#tasks">Manage projects</a></div>{[["Financial Research Evaluation",78,96.9,"On track","12,400"],["Code Reasoning SFT",84,95.8,"At risk","19,240"],["Medical Factuality Review",47,98.7,"On track","5,280"]].map(([name,progress,quality,status,tasks])=><article key={name as string}><div><i>{String(name).split(" ").map(x=>x[0]).slice(0,2).join("")}</i><p><b>{name}</b><span>{tasks} tasks</span></p></div><div><span>Completion <b>{progress}%</b></span><i><em style={{width:`${progress}%`}}/></i></div><strong>{quality}%<small>quality</small></strong><em className={status==="At risk"?"warn":""}>● {status}</em><a href="#analytics">Open →</a></article>)}</section>
          <aside><section className="panel datasetReady" id="datasets"><small>DATASET READY</small><h3>Finance Eval v2.8</h3><p>4,820 newly approved records passed all quality gates.</p><div><span>Schema validated</span><b>✓</b></div><div><span>PII scan complete</span><b>✓</b></div><div><span>Lineage attached</span><b>✓</b></div><a href="#integrations">Review & export →</a></section><section className="panel budgetCard" id="billing"><div className="budgetRing"><span><b>68%</b><small>utilized</small></span></div><p><b>$91,200 remaining</b><span>Across active project budgets</span></p></section></aside>
        </div>
        <section className="portalOperations">{[["workforce","Expert workforce","642 verified experts","View assignments, domains, languages, availability, and verification status."],["tasks","Task operations","8,420 active tasks","Monitor throughput, review queues, deadlines, and failed quality checks."],["quality","Quality control","96.9% agreement","Inspect rubrics, gold tasks, reviewer agreement, revisions, and adjudications."],["analytics","Analytics","42,680 delivered","Explore production, quality, cost, latency, and workforce trends."],["integrations","API & integrations","4 active connections","Manage API keys, webhooks, cloud exports, and dataset delivery."],["alerts","Workspace alerts","2 require attention","Review delivery risk and quality threshold notifications."]].map(([id,title,value,description])=><article className="panel" id={id} key={id}><small>{title.toUpperCase()}</small><h3>{value}</h3><p>{description}</p><a href="#overview">Open workspace view →</a></article>)}</section>
      </div>
    </section>
  </main>
}
