export const metadata={title:"Trainer Dashboard · Trainora AI"};
const trainerNav:[string,string[][]][]=[
  ["DASHBOARD",[["Dashboard","▣"]]],["PROJECTS",[["My Projects","▦"],["Available Projects","◎"],["Applications","♧"]]],
  ["TASKS",[["My Tasks","▤"],["Review Tasks","◫"],["Gold Tasks","◆"]]],["ASSESSMENTS",[["My Assessments","◇"],["Results","◎"]]],
  ["EARNINGS",[["Overview","$"],["Payments","▥"],["Payout Methods","◎"]]],["ACCOUNT",[["Profile","♙"],["Settings","⚙"],["Notifications","♢"]]],["SUPPORT",[["Help Center","?空"],["Contact Support","♧"]]],
];
export default function TrainerPage(){return <main className="guidePortal trainerGuide"><aside className="guideSide"><a className="guideLogo" href="/"><i>⬡</i><b>Trainora AI</b></a><nav>{trainerNav.map(([g,items])=><section key={g}><small>{g}</small>{items.map(([l,i],n)=><a className={g==="DASHBOARD"&&n===0?"active":""} href="#" key={l}><i>{i}</i>{l}</a>)}</section>)}</nav></aside><section className="guideMain"><header className="guideTop"><label>⌕ <input placeholder="Search tasks, projects, or resources…"/></label><div><button>♧</button><button>♢<i/></button><span>OB</span><p><b>Olivia Bennett</b><small>Expert Trainer</small></p></div></header><div className="guideCanvas">
  <header className="guidePageHead"><div><h1>Welcome back, Olivia! 👋</h1><p>Here’s your work summary and next steps.</p></div></header>
  <div className="guideKpis five"><GuideKpiT label="Quality Score" value="96.8%" note="Excellent"/><GuideKpiT label="Tasks Completed" value="1,247" note="+56 this week"/><GuideKpiT label="Earnings This Week" value="$842.50" note="+12% this week"/><GuideKpiT label="Pending Payment" value="$1,256.00" note="Will be paid May 25"/><GuideKpiT label="Active Projects" value="3" note="View projects"/></div>
  <div className="guideTwoCol trainerTop">
    <section className="guideCard"><header><h3>Your Active Tasks</h3></header><div className="activeTaskList">{[["Math Reasoning Evaluation","TASK #C0921","Due in 2h 15m","$4.50"],["Code Generation Review","TASK #C0832","Due in 8h 45m","$6.00"],["Safety Classification","TASK #C0103","Due in 9h 10m","$3.25"]].map(([t,id,due,rate])=><article key={id}><p><b>{t}</b><span>{id}</span><small>{due}</small></p><p><b>{rate}</b><a href="#">Continue</a></p></article>)}</div><button className="guideTextButton">View all tasks</button></section>
    <section className="guideCard"><header><h3>Weekly Task Progress</h3></header><div className="miniLegend"><span><i/>Completed</span><span><i/>Reviewed</span></div><div className="doubleBars">{[90,130,84,160,104,120,72,34].map((v,i)=><div key={i}><i style={{height:`${v}px`}}/><em style={{height:`${v*.72}px`}}/><span>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun",""][i]}</span></div>)}</div></section>
  </div>
  <div className="guideTwoCol trainerMid">
    <section className="guideCard"><header><h3>Recommended Projects</h3></header><div className="recommendList">{[["Medical QA Evaluation","Cinder Research","95% match"],["Legal Reasoning Dataset","Nexora","90% match"],["Multilingual SFT Project","Vector Labs","90% match"]].map(([t,c,m])=><article key={t}><i>◎</i><p><b>{t}</b><span>{c}</span><small>$5.00 – $8.00 per task · 10–15h/week</small></p><em>{m}</em><button>Apply</button></article>)}</div></section>
    <section className="guideCard"><header><h3>Recent Feedback</h3></header><div className="feedbackList">{[["Great attention to detail and accurate scoring.","Math Reasoning Eval · 3h ago","good"],["Your justifications are very helpful.","Code Generation Review · 1d ago","good"],["Try to provide more examples in your reasoning.","Safety Classification · 2d ago","warn"]].map(([t,d,c])=><article key={t}><i className={c}>⊙</i><p><b>{t}</b><span>{d}</span></p></article>)}</div><button className="guideTextButton">View all feedback</button></section>
  </div>
  <div className="guideTwoCol trainerBottom">
    <section className="guideCard"><header><h3>Notifications</h3></header><div className="notificationList">{[["New task available","Math Reasoning Evaluation","2m ago"],["Your task was approved","Code Generation Review","1h ago"],["Payment scheduled","$1,156.00","3h ago"],["New project match","Medical QA Evaluation","1d ago"],["Assessment assigned","Safety & Policy Evaluation","2d ago"]].map(([t,d,time])=><article key={t}><i>⊙</i><p><b>{t}</b><span>{d}</span></p><em>{time}</em></article>)}</div><button className="guideTextButton">View all notifications</button></section>
    <section className="growthCard"><div><h2>Grow your expertise<br/>and unlock more<br/>opportunities.</h2>{["Complete assessments","Maintain high quality","Get advanced projects","Earn quality bonuses"].map(x=><p key={x}>✓ {x}</p>)}<button>View my progress →</button></div><div className="awardSeal">✓</div></section>
  </div>
 </div></section></main>}
function GuideKpiT({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
