import { notFound } from "next/navigation";
import { DashboardIcon, type DashboardIconName } from "../../components/DashboardIcon";
import { AdminSidebar } from "../AdminSidebar";

type Section = {
  label: string;
  icon: DashboardIconName;
  eyebrow: string;
  description: string;
  metrics: Array<[string, string, string]>;
  actions: Array<[string, string]>;
  activity: Array<[string, string, string]>;
};

const sections: Record<string, Section> = {
  applicants: { label:"Applicants",icon:"user",eyebrow:"PEOPLE / QUALITY GATES",description:"Review every application, identity check, credential, assessment, and approval decision.",metrics:[["Awaiting review","132","Human decision required"],["Identity pending","18","Government ID or liveness"],["Assessment passed","84%","Current applicant cohort"],["Risk flags","16","Manual investigation"]],actions:[["Open approval command center","/admin#applicants"],["Review role permissions","/roles"]],activity:[["Identity packet submitted","Medical applicant · 8m ago","Review"],["Assessment failed integrity gate","Software engineering · 31m ago","Investigate"],["Credential evidence updated","Legal applicant · 1h ago","Open"]]},
  trainers: { label:"Trainers",icon:"trainer",eyebrow:"PEOPLE / APPROVED NETWORK",description:"Manage approved experts, quality standing, project eligibility, probation, and suspensions.",metrics:[["Approved trainers","12,847","Across 150 disciplines"],["Active this week","8,392","65.3% utilization"],["Quality probation","246","Enhanced sampling"],["Suspended","31","Risk or quality review"]],actions:[["View applicant pipeline","/admin/applicants"],["Open trainer marketplace","/trainer"]],activity:[["Quality threshold recovered","Trainer QA-1042 · 14m ago","View"],["Calibration renewal due","82 trainers · 2h ago","Assign"],["New discipline approved","Nuclear engineering · today","Review"]]},
  clients: { label:"Clients",icon:"client",eyebrow:"PEOPLE / ENTERPRISE ACCOUNTS",description:"Control client organizations, workspaces, budgets, projects, access, and delivery health.",metrics:[["Active clients","128","14 enterprise plans"],["Open projects","312","Across all workspaces"],["At-risk delivery","9","Requires account action"],["Monthly volume","$1.84M","Approved project spend"]],actions:[["Open client workspace","/client"],["Review projects","/admin/projects"]],activity:[["New workspace provisioned","Northstar Systems · today","Open"],["Budget threshold reached","Helix AI · 1h ago","Review"],["Project scope updated","Vector Labs · 3h ago","View"]]},
  reviewers: { label:"Reviewers",icon:"reviewer",eyebrow:"PEOPLE / REVIEW OPERATIONS",description:"Manage reviewer eligibility, assignment capacity, calibration, and adjudication authority.",metrics:[["Active reviewers","2,186","97.8% agreement"],["Queue capacity","18,420","Reviews per day"],["Calibration due","74","Within seven days"],["Adjudicators","148","Senior authority"]],actions:[["Open reviewer workspace","/reviewer"],["View calibration","/admin/calibration"]],activity:[["Adjudication completed","Financial evaluation · 12m ago","Open"],["Reviewer recalibrated","Medical domain · 42m ago","View"],["Rubric feedback raised","Safety project · 1h ago","Resolve"]]},
  projects: { label:"Projects",icon:"projects",eyebrow:"DELIVERY / PORTFOLIO",description:"Track project scopes, clients, workforce, deadlines, budgets, and dataset readiness.",metrics:[["Active projects","128","43 enterprise clients"],["On schedule","91%","Seven-day trend"],["Dataset ready","18","Awaiting export"],["Delivery risks","12","Quality or capacity"]],actions:[["Open client portfolio","/client#projects"],["Manage jobs","/admin/jobs"]],activity:[["Milestone completed","Financial Research Eval · 18m ago","Open"],["Scope change requested","Medical Factuality · 1h ago","Review"],["Capacity increased","Code Generation · today","View"]]},
  tasks: { label:"Tasks",icon:"tasks",eyebrow:"DELIVERY / TASK OPERATIONS",description:"Monitor throughput, assignment, completion, review queues, and failed quality gates.",metrics:[["In progress","18,500","43% of active work"],["Under review","12,350","29% of active work"],["Revision","6,482","15% of active work"],["Approved","5,300","13% of active work"]],actions:[["Open trainer tasks","/trainer#tasks"],["Review quality dashboard","/admin/quality"]],activity:[["Throughput alert resolved","Code evaluation · 9m ago","View"],["Gold-task failure detected","Trainer cohort · 22m ago","Investigate"],["Review queue reassigned","Medical project · 1h ago","Open"]]},
  reviews: { label:"Reviews",icon:"feedback",eyebrow:"DELIVERY / HUMAN REVIEW",description:"Control review queues, disagreement handling, revisions, and senior adjudication.",metrics:[["Awaiting review","1,342","Across 43 projects"],["Agreement","98.4%","Seven-day average"],["Adjudications","27","Open cases"],["Revision rate","2.1%","Within target"]],actions:[["Open reviewer queue","/reviewer"],["Open quality controls","/admin/quality"]],activity:[["Senior adjudication assigned","REV-4104 · 6m ago","Open"],["Consensus reached","Legal benchmark · 27m ago","View"],["Revision requested","Safety evaluation · 1h ago","Review"]]},
  quality: { label:"Quality",icon:"quality",eyebrow:"QUALITY / COMMAND CENTER",description:"Measure agreement, acceptance, revisions, gold tasks, risk, and traceability.",metrics:[["Review agreement","98.4%","Above 97% target"],["Task acceptance","96.8%","Seven-day average"],["Revision rate","2.1%","Below 3% limit"],["Traceability","100%","Submission lineage"]],actions:[["Open quality charts","/admin#quality"],["Manage gold tasks","/admin/gold-tasks"]],activity:[["Quality drift detected","Linguistics cohort · 15m ago","Investigate"],["Threshold increased","Financial project · today","View"],["Reviewer agreement recovered","Medicine · today","Open"]]},
  assessments: { label:"Assessments",icon:"assessment",eyebrow:"QUALITY / PRE-SCREENING",description:"Create versioned tests, manage pass thresholds, attempts, integrity, and manual review.",metrics:[["Active versions","6","Across core disciplines"],["Pass rate","74%","Current cohort"],["Integrity flags","21","Manual review"],["Median score","86%","Passed attempts"]],actions:[["Create assessment version","/admin#assessment-admin"],["View applicant results","/admin/applicants"]],activity:[["New version activated","Core Quality v4 · today","Open"],["Fast completion flagged","Attempt A-1049 · 28m ago","Review"],["Manual score adjusted","Medical test · 1h ago","Audit"]]},
  "gold-tasks": { label:"Gold tasks",icon:"target",eyebrow:"QUALITY / HIDDEN CONTROLS",description:"Maintain benchmark tasks used to continuously validate trainers and reviewers.",metrics:[["Active gold tasks","1,840","Across 44 disciplines"],["Exposure rate","4.2%","Of production tasks"],["Failure alerts","16","Immediate review"],["Refresh due","92","Within 30 days"]],actions:[["Open quality dashboard","/admin/quality"],["Open trainer qualification","/trainer#gold-tasks"]],activity:[["Benchmark refreshed","Clinical safety · today","View"],["Exposure cap reached","Legal dataset · 2h ago","Rotate"],["Failure cluster detected","Code security · 4h ago","Investigate"]]},
  calibration: { label:"Calibration",icon:"reports",eyebrow:"QUALITY / CONSISTENCY",description:"Schedule and inspect versioned calibration exercises for trainers and reviewers.",metrics:[["Current","94.8%","Eligible workforce"],["Due soon","156","Within 14 days"],["Overdue","38","Access restricted"],["Agreement","97.9%","Calibration benchmark"]],actions:[["Open reviewer calibration","/reviewer#calibration"],["Manage assessments","/admin/assessments"]],activity:[["Calibration passed","Reviewer R-204 · 8m ago","View"],["Rubric version changed","Financial v2.1 · today","Review"],["Access paused","38 overdue accounts · today","Resolve"]]},
  earnings: { label:"Earnings",icon:"sales",eyebrow:"FINANCE / WORKFORCE COST",description:"Monitor trainer earnings, approved work, bonuses, and payment readiness.",metrics:[["This month","$1.24M","Approved earnings"],["Pending approval","$86,420","Quality review"],["Quality bonuses","$42,180","Top performers"],["Payment holds","12","Requires action"]],actions:[["Open trainer earnings","/trainer#earnings"],["Review invoices","/admin/invoices"]],activity:[["Weekly earnings approved","Batch 2025-21 · today","View"],["Quality bonus issued","Medical cohort · today","Audit"],["Payment hold placed","Identity mismatch · 1h ago","Review"]]},
  invoices: { label:"Invoices",icon:"invoices",eyebrow:"FINANCE / CLIENT BILLING",description:"Manage project invoices, approvals, credits, tax records, and payment status.",metrics:[["Open invoices","38","$418,200 total"],["Paid this month","$1.62M","96 invoices"],["Overdue","7","$72,440 total"],["Credits","$8,210","Current month"]],actions:[["Open client billing","/client#billing"],["Review earnings","/admin/earnings"]],activity:[["Invoice paid","INV-2841 · 12m ago","View"],["Credit approved","Northstar AI · 1h ago","Audit"],["Invoice overdue","Helix AI · 2d ago","Follow up"]]},
  disputes: { label:"Disputes",icon:"disputes",eyebrow:"FINANCE / RESOLUTION",description:"Resolve trainer payment, task acceptance, rate, and client billing disputes.",metrics:[["Open disputes","27","11 high priority"],["Median resolution","18h","Within 24h target"],["Trainer claims","19","Current queue"],["Client claims","8","Current queue"]],actions:[["Open support tickets","/admin/tickets"],["Review audit logs","/admin/audit-logs"]],activity:[["Evidence submitted","DSP-2091 · 11m ago","Review"],["Payment correction approved","DSP-2077 · 1h ago","View"],["Client response received","DSP-2049 · today","Open"]]},
  tickets: { label:"Support tickets",icon:"support",eyebrow:"OPERATIONS / SUPPORT",description:"Prioritize account, project, quality, payment, and security support cases.",metrics:[["Open tickets","86","14 urgent"],["First response","22m","Median today"],["Resolved today","119","94% satisfaction"],["Escalated","9","Specialist review"]],actions:[["Review disputes","/admin/disputes"],["Open alerts","/admin/alerts"]],activity:[["Security ticket escalated","TKT-9812 · 5m ago","Open"],["Trainer question answered","TKT-9804 · 18m ago","View"],["Client issue resolved","TKT-9782 · 41m ago","Review"]]},
  alerts: { label:"Alerts",icon:"notifications",eyebrow:"OPERATIONS / ALERTS",description:"Investigate quality, fraud, delivery, capacity, storage, and payment alerts.",metrics:[["Critical","3","Immediate action"],["High","13","Today"],["Medium","28","This week"],["Resolved","164","Last seven days"]],actions:[["Open fraud detection","/admin/fraud"],["Review audit logs","/admin/audit-logs"]],activity:[["High rejection rate","Code Generation · now","Investigate"],["Unusual task speed","7 trainers · 4m ago","Review"],["Payment failure cluster","12 payments · 31m ago","Resolve"]]},
  "audit-logs": { label:"Audit logs",icon:"audit",eyebrow:"OPERATIONS / TRACEABILITY",description:"Search immutable records of decisions, data access, changes, and privileged actions.",metrics:[["Events today","18,402","Across all services"],["Admin actions","284","Privileged events"],["Data access","6,140","Protected resources"],["Retention","365 days","Current policy"]],actions:[["Open settings","/admin/settings"],["Review fraud signals","/admin/fraud"]],activity:[["Applicant approved","Admin · 6m ago","Inspect"],["Document accessed","Restricted evidence · 12m ago","Inspect"],["Job source synchronized","Greenhouse · 21m ago","Inspect"]]},
  fraud: { label:"Fraud detection",icon:"fraud",eyebrow:"OPERATIONS / TRUST & SAFETY",description:"Investigate identity, duplicate-account, automation, velocity, and payment risk.",metrics:[["Active signals","16","10 accounts affected"],["High risk","3","Access restricted"],["In review","8","Analyst queue"],["Cleared today","21","False positives"]],actions:[["Open applicant review","/admin/applicants"],["Review alerts","/admin/alerts"]],activity:[["Duplicate identity signal","Applicant · 7m ago","Investigate"],["Impossible task velocity","Trainer · 18m ago","Review"],["Payment name mismatch","Trainer · 46m ago","Resolve"]]},
  settings: { label:"Settings",icon:"settings",eyebrow:"OPERATIONS / PLATFORM",description:"Control quality defaults, retention, access, notifications, integrations, and platform policies.",metrics:[["Environment","Production","Private deployment"],["Admin access","1 account","Allowlisted"],["Retention","365 days","Evidence policy"],["Integrations","4 active","Operational"]],actions:[["Manage job APIs","/admin/jobs"],["Review roles & access","/roles"]],activity:[["Quality threshold updated","90% default · today","View"],["Retention policy reviewed","No changes · yesterday","Audit"],["Admin access checked","Allowlist · yesterday","Open"]]},
};

export default async function AdminSectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section: slug } = await params;
  const section = sections[slug];
  if (!section) notFound();
  return <main className="guidePortal adminRoutePage">
    <AdminSidebar active={section.label}/>
    <section className="guideMain">
      <header className="guideTop routeTopbar"><label><DashboardIcon name="search" size={18}/><input placeholder={`Search ${section.label.toLowerCase()}…`}/></label><div><a href="/roles"><DashboardIcon name="roles" size={18}/> Roles</a><a href="/admin/alerts"><DashboardIcon name="notifications" size={18}/></a><span>AM</span><p><b>Alex Morgan</b><small>Super Admin</small></p></div></header>
      <div className="guideCanvas adminSectionCanvas">
        <header className="adminSectionHero"><span><DashboardIcon name={section.icon} size={25}/></span><div><small>{section.eyebrow}</small><h1>{section.label}</h1><p>{section.description}</p></div></header>
        <section className="roleKpis adminRouteKpis">{section.metrics.map(([label,value,note])=><article key={label}><span>{label}</span><b>{value}</b><small>{note}</small></article>)}</section>
        <div className="adminSectionGrid">
          <section className="controlPanel adminActivityPanel"><header><span><DashboardIcon name="activity" size={20}/></span><div><small>LIVE OPERATIONS</small><h2>Recent activity</h2></div></header>{section.activity.map(([title,detail,action])=><article key={title}><i><DashboardIcon name={section.icon} size={18}/></i><p><b>{title}</b><span>{detail}</span></p><a href={section.actions[0][1]}>{action}<DashboardIcon name="arrow" size={15}/></a></article>)}</section>
          <aside className="controlPanel adminQuickActions"><header><span><DashboardIcon name="sparkles" size={20}/></span><div><small>QUICK ACTIONS</small><h2>Continue working</h2></div></header>{section.actions.map(([label,href])=><a href={href} key={label}><DashboardIcon name="arrow" size={17}/><span><b>{label}</b><small>Open the connected workspace</small></span></a>)}</aside>
        </div>
      </div>
    </section>
  </main>;
}
